module IconsHelper
  def icons
    [
      'arrow-down',
      'arrow-left',
      'arrow-right',
      'arrow-up',
      'arrow-circle-down',
      'arrow-circle-left',
      'arrow-circle-right',
      'arrow-circle-up',
      'arrow-fill-down',
      'arrow-fill-left',
      'arrow-fill-right',
      'arrow-fill-up',
      'info',
      'info-fill',
      'archive',
      'document',
      'download',
      'email',
      'error',
      'feedback',
      'help',
      'lock',
      'location',
      'note',
      'plus',
      'plus-circle',
      'projects-resrc',
      'search',
      'settings',
      'star',
      'tick',
      'volunteers',
      'warning'
    ]
  end
end
